[package]
name = "azure_sdk_for_rust"
version = "0.1.3"
description = "Rust wrappers around Microsoft Azure REST APIs"
readme = "README.md"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>"]
license = "Apache-2.0"
repository = "https://github.com/MindFlavor/AzureSDKForRust"
documentation = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"

[[bin]]
name = "main"
doc = false

[dependencies]
chrono = "0.2.19"
rust-crypto = "0.2.34"
rustc-serialize = "0.3.16"
RustyXML = "0.1.1"
mime = "0.1.1"
log = "0.3.5"
env_logger = "0.3.2"
uuid = "0.1.18"
time = "0.1.34"
url = "0.5.4"

# clippy="*"

[dependencies.hyper]
version = "0.7.2"
default-features = true
