[package]
name           = "azure_sdk_for_rust"
version        = "0.6.0"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage       = "https://github.com/MindFlavor/AzureSDKForRust"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[dependencies]
RustyXML       = "0.1.1"
base64         = "0.7.0"
chrono         = "0.4.0"
env_logger     = "0.4.3"
futures        = "0.1.17"
hyper          = "0.11.6"
hyper-tls      = "0.1.2"
log            = "0.3.8"
mime           = "0.3.5"
native-tls     = "0.1.4"
quick-error    = "1.2.1"
rust-crypto    = "0.2.36"
serde          = "1.0.19"
serde_derive   = "1.0.19"
serde_json     = "1.0.6"
time           = "0.1.38"
tokio-core     = "0.1.10"
url            = "1.6.0"
uuid           = "0.5.1"

[features]
test_e2e       = []
